version: '3.1'
#test
services:
  php:
    image: customphpalpine
    restart: always
    environment:
      - HOSTNAME=192.168.56.108:3306
      - USERNAME=futureprogram
      - PASSWORD=Future4-0
      - DBNAME=crud_laundry
    volumes:
      - ./:/app
      - phpsession:/tmp
    working_dir: /app
  web:
    restart: always
    image: customnginx
    volumes:
      - ./:/app
    ports:
      - 80
  loadbalancer:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports: 
      - 80:80
